In [88]:
import numpy as np

#create const arrays
a=np.zeros((2,4),dtype=np.int64)
print(a)
a=np.ones((2,4))
print(a)

# array of constants
a=np.full((2,4),5)
print(a)

# identity matrix
a=np.eye(4)   #is a square matrix so only 1 arguement is given
print(a)

# random matrix
a=np.random.random((3,4)) #generate random floats number in the half-open interval [0.0, 1.0)
print(a)
a=np.random.randn(3,4,2)  #gaussian random variables from the "standard normal" distribution.
print(a)
a=np.random.randint(3,10,(4,4)) # int between low and high
print(a)

[[0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.14038694 0.19810149 0.80074457 0.96826158]
 [0.31342418 0.69232262 0.87638915 0.89460666]
 [0.08504421 0.03905478 0.16983042 0.8781425 ]]
[[[-0.17242821 -0.87785842]
  [ 0.04221375  0.58281521]
  [-1.10061918  1.14472371]
  [ 0.90159072  0.50249434]]

 [[ 0.90085595 -0.68372786]
  [-0.12289023 -0.93576943]
  [-0.26788808  0.53035547]
  [-0.69166075 -0.39675353]]

 [[-0.6871727  -0.84520564]
  [-0.67124613 -0.0126646 ]
  [-1.11731035  0.2344157 ]
  [ 1.65980218  0.74204416]]]
[[3 4 4 8]
 [6 3 3 8]
 [8 9 7 8]
 [9 5 7 6]]


In [89]:
#shape and reshape 
print(a.shape)
#note that shape is not a method .it is an attribute but to use as a method use the below code
print(np.shape(a))
#it turns out this is neither a row vector nor a column vector
#it is a linear array (1-D)
# instead its a different data structure called rand 1 array which doesn't behave like a normal vector as shown below
a=np.random.randn(5)
a=a.reshape((5,1))  #reshape returns ndim array with changed shape
a.resize((5,1))  #change same array itself
print(a,a.shape)
b = np.array([(8,9,10),(11,12,13)])
print(b,b.shape)
b=b.reshape((3,2))
print(b)
c=np.array([1,2])
print(c,c.shape)

(4, 4)
(4, 4)
[[ 0.85723427]
 [ 0.18393058]
 [-0.41611158]
 [ 1.25005005]
 [ 1.24829979]] (5, 1)
[[ 8  9 10]
 [11 12 13]] (2, 3)
[[ 8  9]
 [10 11]
 [12 13]]
[1 2] (2,)


# slicing

In [91]:
#slicing of 2D array
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[ : , 1])  # return matrix with all rows of given matrix with column value 1
print(a[0][3],a[0,3]) #Both are same
a[ : , 1:3]=1  #assignment also works 

#this type of slicing doesn't work with lists..only for numpy
print(a)

a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])
#array(1,2,3,4) is your index 0 and (3,4,5,6) is index 1 of the python numpy array. 
#Therefore, we have printed the second element from the zeroth index
print(a[0:,2])
#this gives us the 2nd element from the zeroth and first index of the array.
#colon represents all the rows, including zero
a=np.array([(8,9),(10,11),(12,13)])
print(a[0:2,1].shape)
#if we have one more row and we don’t want to get its 2nd element printed just as the image above
#NOTE- this is valid when array is 2d that is it has m rows and n columns unlike arrays like [1,[2,3]].
#it is not a 2-d numpy array instead if a rank 1 array as if u print its shape it will print (2,)

[2 4]
4 4
[[1 1 1 4]
 [3 1 1 6]]
3
[3 5]
(2,)


# mathematical operations

In [92]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])

#element wise add,subt,mult,div
print(a+b)
print(np.add(a,b))  #shape has to be same
print(a-b)
print(np.subtract(a,b))
print(a*b)
print(np.multiply(a,b))
print(a/b)
print(np.divide(a,b))
a=np.array([(1,2,3),(3,4,5)])
print(np.sqrt(a))  #element wise sqrt
print(np.std(a))
#np.sqrt() calculate square root of all the elements
#np.std() calculate standard deviation i.e how much each element varies from the mean value of the python numpy array
#matrix multiplication

# dot product of 2 rank1 array=scalar because it treats one as x,1 and other 1,x arrays
a=np.array([[1,2,3],[3,4,5]])
b=np.array([[3,4],[4,2],[3,5]])
print(a.dot(b),np.dot(a,b))

print(a.T)
#transpose is exactly the same as a which is not expected for a matrix

[[ 5  7]
 [ 9 11]]
[[ 5  7]
 [ 9 11]]
[[-3 -3]
 [-3 -3]]
[[-3 -3]
 [-3 -3]]
[[ 4 10]
 [18 28]]
[[ 4 10]
 [18 28]]
[[0.25       0.4       ]
 [0.5        0.57142857]]
[[0.25       0.4       ]
 [0.5        0.57142857]]
[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056
[[20 23]
 [40 45]] [[20 23]
 [40 45]]
[[1 3]
 [2 4]
 [3 5]]


 # statistical functions

In [93]:
a= np.array([(1,2,3),(3,4,5)])
print(a.min())
print(a.max())
print(a.sum())
print(np.max(a))
#a.sum() prints all the elements of a multidimensional array
#NOTE the word multidimensional.If you perform this operation on a list that is not a multi/uni dimensional 
#array like rank 1 array then you will not get desired results.

#more maths
a= np.array([1,2,3])
print(np.exp(a))     #exponential function
print(np.log(a))     #natural log
print(np.log10(a))   #log base 10

1
5
18
5
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]


In [94]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
#Specify axis for the direction in case of multidim array
new_array=np.min(a,axis=0)
print(new_array,new_array.shape)    #returns rank1 array only!! BEWARE
print(np.min(a,axis=1))

b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0] (4,)
[1 0]
3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [95]:
c = np.array([1,5,4,2,0])
print(np.median(c))

# Mean vs Average is Weighted
print(np.mean(c))

# Weights 
w = np.array([1,1,1,1,1])
print(np.average(c,weights=w))
print(np.average(c))

# Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

#Inbuilt Function
dev= np.std(c)
print(dev)

#Variance
print(myStd**2)
print(np.var(c))

2.0
2.4
2.4
2.4
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


In [96]:
#in numpy rows are called as axis 1 and the columns are called as axis 0
a= np.array([(1,2,3),(3,4,5)])
print(np.sum(a))
print(a.sum(axis=0))
print(a.sum(axis=1))
#the sum of all the columns are added where 1+3=4, 2+4=6 and 3+5=8. Similarly, if you replace the axis by 1, 
#then it will print [6 12] where all the rows get added.

18
[4 6 8]
[ 6 12]


# More functions and attributes

In [97]:
b=np.ndim([[1,2],3,4])
c=np.ndim([[1,2],[2,3]])
print(b,c)
#np.ndim() returns the no of dim.it can't be used like an attribute like shape which can 
#be used as both method & attr.
print(a.dtype,np.size(a),a.size,a.itemsize)
#a.dtype find the data type of the elements that are stored in an array
#a.itemsize calculate the byte size of each element
#a.size calculate total no of elements
c=np.array([1,2.2])
print(c.dtype,c.itemsize)
#it seems as if c has 1 int and 1 float but python considers both as float when one of them 
#is float

1 2
int64 6 6 8
float64 8


In [98]:
#special functions
print(np.pi)
#np.pi is the value of pi constant
y=np.sin(x)
z=np.tan(x)

a=np.linspace(1,3,10)
print(a,a.shape)
#np.linspace() is a operation in python numpy which returns evenly spaced numbers over a specified interval

3.141592653589793
[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ] (10,)


In [99]:
#Vertical & Horizontal Stacking
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(8,9,7),(11,12,13)])
print(np.vstack((x,y)))
print(np.hstack((x,y)))
print(np.stack((x,y),axis=0))
print(np.stack((x,y),axis=1))
#to concatenate two arrays and not just add them, you can perform it using two ways -
#vertical stacking and horizontal stacking

[[ 1  2  3]
 [ 3  4  5]
 [ 8  9  7]
 [11 12 13]]
[[ 1  2  3  8  9  7]
 [ 3  4  5 11 12 13]]
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 8  9  7]
  [11 12 13]]]
[[[ 1  2  3]
  [ 8  9  7]]

 [[ 3  4  5]
  [11 12 13]]]


In [100]:
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel(),x.ravel().shape)
#x.ravel() is used to convert one numpy array into a single column i.e ravel.
#it returns a rank 1 array .Be careful
#this function works fine for rank 1 array as well

[1 2 3 3 4 5] (6,)


In [101]:
d=np.arange(4, 20, 3)
print(d)
#np.arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval.
#start:start of interval range. By default start = 0
#stop:end of interval range(NOTE THAT STOP VALUE IS NOT INCLUDED IN THE ARRAY BUT START VALUE IS)
#step:step size of interval. By default step size = 1,  
#dtype : type of output array

print(np.arange(5)) #from 0 to 4 elements

#similar to linespace but the only difference is that in linespace we provide no of elements that the array should 
#have and both start and stop value is included unlike inarange in which resulted array doesn't have stop value
print(d.shape)
#np.arange() returns a rank 1 array
d=d.reshape((1,6))
print(d,d.shape)

[ 4  7 10 13 16 19]
[0 1 2 3 4]
(6,)
[[ 4  7 10 13 16 19]] (1, 6)


In [102]:
import numpy as np
import pandas as pd
a=[1,2,3]
b=[4,5,6]
c=np.c_[a,b] #note  that np.c_ is not a callable function. square brackets are used
print(c)
print(pd.DataFrame(c))

[[1 4]
 [2 5]
 [3 6]]
   0  1
0  1  4
1  2  5
2  3  6


# Numpy Random Module 
<ul><li>
rand : Random values in a given shape.</li><li>
randn : Return a sample (or samples) from the “standard normal” distribution.</li><li>
randint : Return random integers from low (inclusive) to high (exclusive).</li><li>
random : Return random floats in the half-open interval [0.0, 1.0)</li><li>
choice : Generates a random sample from a given 1-D array</li><li>
Shuffle : Shuffles the contents of a sequence</ul>

In [103]:
a = np.arange(10) + 5
print(a)

np.random.seed(1)
np.random.shuffle(a)
print(a)

#Returns values from a Standard Normal Distributions
a = np.random.randn(2,3)
print(a)

a = np.random.randint(5,10,3)
print(a)

#Randoly pick one element from a array
element = np.random.choice([1,4,3,2,11,27])
print(element)


[ 5  6  7  8  9 10 11 12 13 14]
[ 7 14 11  9  5  8  6 12 13 10]
[[ 1.5827523  -1.04514683  0.25759352]
 [-1.9593946  -1.50780766 -0.31529207]]
[7 9 6]
4
