## Linear Math -Vector, Matrix, Tensor, Matrix Product, Inverse Matrix

### Basic library, function import

In [7]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


In [8]:
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon
import numpy as np
import tensorflow as tf


def vector_plot(vecs, xlim, ylim, cols=["#1190FF", "#FF9A13"], alpha=1):
    plt.rc_context({'axes.edgecolor':'orange', 'xtick.color':'red', 'ytick.color':'red'})
    plt.axvline(x=0, color='k', zorder=0)
    plt.axhline(y=0, color='k', zorder=0)

    for i in range(len(vecs)):
        if (isinstance(alpha, list)):
            alpha_i = alpha[i]
        else:
            alpha_i = alpha
        x = np.concatenate([[0,0],vecs[i]])
        plt.quiver([x[0]],
                   [x[1]],
                   [x[2]],
                   [x[3]],
                   angles='xy', scale_units='xy', scale=1, color=cols[i],
                   alpha=alpha_i)
        plt.ylim(-xlim, xlim)
        plt.xlim(-ylim, ylim)
        plt.grid()

def plot_vector2d(vector2d, origin=[0, 0], **options):
    return plt.arrow(origin[0], origin[1], vector2d[0], vector2d[1],
                   head_width=0.2, head_length=0.3, length_includes_head=True,
                   **options)

def plot_transform(P_before, P_after, text_before, text_after, name, color=['#FF9A13', '#1190FF'], axis = [0, 5, 0, 4], arrows=False):
    if arrows:
        for vector_before, vector_after in zip(tf.transpose(P_before), tf.transpose(P_after)):
            plot_vector2d(vector_before, color="#FF9A13", linestyle="--")
            plot_vector2d(vector_after, color="#1190FF", linestyle="-")
        plt.rc_context({'axes.edgecolor':'orange', 'xtick.color':'red', 'ytick.color':'red'})
        plt.gca().add_artist(Polygon(tf.transpose(P_before), alpha=0.2))
        plt.gca().add_artist(Polygon(tf.transpose(P_after), alpha=0.3, color="#FF9A13"))
        plt.text(-.25, 1, text_before, size=18, color=color[1])
        plt.text(1.5, 0, text_after, size=18, color=color[0])
        plt.title(name, color='w')
        plt.axis(axis)
        plt.grid()

def evaluate(tensors):
    """Evaluates Tensor or EagerTensor to Numpy `ndarray`s.
    Args:
    tensors: Object of `Tensor` or EagerTensor`s; can be `list`, `tuple`,
      `namedtuple` or combinations thereof.

    Returns:
      ndarrays: Object with same structure as `tensors` except with `Tensor` or
        `EagerTensor`s replaced by Numpy `ndarray`s.
    """
    return tf.nest.pack_sequence_as(tensors,[t.numpy() if tf.is_tensor(t) else t for t in tf.nest.flatten(tensors)])

Linear Algebra is a field of mathematics that deals with linear equations, linear functions, and expressions through matrices and vector spaces.

Machine learning relies heavily on linear algebra, it is important to understand vectors and matrices

In [9]:
import tensorflow as tf
import sys
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### 1-1. Scalars, Vectors, Matrices and Tensor
- **Saclars**: Single number
- **Vectors**: Array of numbers
  - Numbers are sorted in order, and each number can be identified in order by index
  - Vector is an arrow that can express a quantity with both size and direction (the direction of the arrow is the size, the direction is the direction)
- **Matrices**: Matrix is a two-dimensional array of numbers, each element identified by two indices instead of one
  - If matrix A has height m and width n, then  $A\ in\ \mathbb {R}^{m \times n}$
  - The elements of the matrix $A_{m,n}$ 

![Scalars, Vectors, Matrices and Tensors](https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png)

- **Tensor**: Array of numbers arranged in a regular grid with variable number of axes.A tensor is an array with more than 2 axis.
  - $A_{i,j,k}$ :location $(i, j, k) $Tensor of $A$
  - Vectors can be represented by three components: $(x, y, z)$

![Tensors](https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201b.PNG)





$$\color{Orange}{C=A+B\ where\ C_{i, j} = A_{i,j} + B_{i,j} \tag{1}}$$
- Tensor in Tensorflow
  - Rank 0 Tensor: Scalar
  - Rank 1 Tensor: Vector
  - Rank 2 Tensor: Matrix
  - Rank 3 Tensor: 3-Tensor
  - Rank n Tensor: n-Tensor

In [10]:
# ones 3x3 rank 2 tensor
rank_2_tensor_A = tf.ones([3,3], name='MatrixA')
print("3x3 Rank 2 Tensor A: \n{} \n".format(rank_2_tensor_A))

# 3x3 rank 2 tensor
rank_2_tensor_B = tf.constant([[1,2,3], [4,5,6], [7,8,9]], name='MatrixB', dtype=tf.float32)
print("3x3 Rank 2 Tensor B: \n{} \n".format(rank_2_tensor_B))

# add two tensor
rank_2_tensor_C = tf.add(rank_2_tensor_A, rank_2_tensor_B, name='MatrixC')
print("Rank 2 Tensor C with shape={} and elements: \n{}".format(rank_2_tensor_C.shape, rank_2_tensor_C))

3x3 Rank 2 Tensor A: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

3x3 Rank 2 Tensor B: 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

Rank 2 Tensor C with shape=(3, 3) and elements: 
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [11]:
two_by_three = tf.ones([2,3])
print("2x3 Rank 2 Tensor two_by_three: \n{} \n".format(two_by_three))
try:
    incompatible_tensor = tf.add(two_by_three, rank_2_tensor_B)
except:
    print("Imcompatible shapes to add with two_by_three of shape {}\
    and 3x3 Rank 2 Tensor B of shape{}".format(two_by_three.shape, rank_2_tensor_B.shape))

2x3 Rank 2 Tensor two_by_three: 
[[1. 1. 1.]
 [1. 1. 1.]] 

Imcompatible shapes to add with two_by_three of shape (2, 3)  and 3x3 Rank 2 Tensor B of shape(3, 3)


You can add a scalar to the matrix or multiply the matrix by a scalar by performing the corresponding operation on each element of the matrix.$$\color{orange}{D=a \cdot B+c\ where\ D_{i,j}=a \cdot B_{i,j}+c \tag{2}}$$

In [12]:
# scalar a,c and Matrix B
rank_0_tensor_a = tf.constant(2, name="scalar_a", dtype=tf.float32)
rank_2_tensor_B = tf.constant([[1,2,3], [4,5,6], [7,8,9]], name="MatrixB", dtype=tf.float32)
rank_0_tensor_c = tf.constant(3, name="scalar_c", dtype=tf.float32)

# aB
multiply_scalar = tf.multiply(rank_0_tensor_a, rank_2_tensor_B)

# aB+c
rank_2_tensor_D = tf.add(multiply_scalar, rank_0_tensor_c, name="MatrixD")

print("""Original Rank 2 Tensor B: \n{0} \n\nScalar a: {1} \n\
Rank 2 Tensor for aB: \n{2} \n\nScalar c: {3} \n\
Rank 2 Tensor D = aB+c: \n{4} )""".format(rank_2_tensor_B, rank_0_tensor_a, 
                                          multiply_scalar, rank_0_tensor_c, rank_2_tensor_D))

Original Rank 2 Tensor B: 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

Scalar a: 2.0 
Rank 2 Tensor for aB: 
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]] 

Scalar c: 3.0 
Rank 2 Tensor D = aB+c: 
[[ 5.  7.  9.]
 [11. 13. 15.]
 [17. 19. 21.]] )


### Tanspose

 Transpose of a matrix is a matrix in which rows and columns are swapped along a diagonal line called the main diagonal.

Change the $A$ matrix to $A\ top$ and define as follows
$$(A^\top)_{i,j} = A_{j,i}$$

In numpy there also exists Transpose of a tensor- It reverses the shape of the tensor.
If shape was (x,y,z,d) then shape of transpose will be (d,z,y,x). However, you can also specify the axis as well in the transpose function.

In [13]:
# rank 2 Matrix E
rank_2_tensor_E = tf.constant([[1,2,3], [4,5,6]])

# transpose Matrix E
transpose_E = tf.transpose(rank_2_tensor_E, name="transposeE")

print("""Rank 2 Tensor E of shape: {0} and elements: \n{1}\n\
Tanspose of Rank 2 Tensor E of shape: {2} and elements: \n{3}""".format(rank_2_tensor_E.shape, rank_2_tensor_E,
                                                                        transpose_E.shape, transpose_E))

Rank 2 Tensor E of shape: (2, 3) and elements: 
[[1 2 3]
 [4 5 6]]
Tanspose of Rank 2 Tensor E of shape: (3, 2) and elements: 
[[1 4]
 [2 5]
 [3 6]]


### Broadcasting -
broadcasting is not supported by python lists. It is supported by only numpy vectors/matrices/tensors.
- Adding scalar to a vector adds that scalar to each element of vector
- Adding vector to a matrix will add the vector to each row or to each column of matrix depending on the shape of vector

In deep learning, another matrix with $C_{i,j} = A_{i,j}+b_j$ can be created by adding a matrix and a vector.
That is, the vector b is added to each row of the matrix, and implicit copying of b to multiple locations is called **broadcasting**.

In [14]:
# rank 1 vector b
rank_1_tensor_b = tf.constant([[4.], [5.], [6.]])
# broadcast, F = A + b
rank_2_tensor_F = tf.add(rank_2_tensor_A, rank_1_tensor_b, name="broadcastF")

print("""Rank 2 tensor A: \n{0}\n \nRank 1 Tensor b: \n{1}\
\nRank 2 tensor F = A+b: \n{2}""".format(rank_2_tensor_A, rank_1_tensor_b, rank_2_tensor_F))

Rank 2 tensor A: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
 
Rank 1 Tensor b: 
[[4.]
 [5.]
 [6.]]
Rank 2 tensor F = A+b: 
[[5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]]


### 1-2. Multiplying Matrices and Vectors
To define matrix product of matrices $A$, $B$, and $A$, $A$ must have the same number of columns as $B$

If the shape of $A$ is $m\times n$ and the shape of $B$ is $n \times p$, then the shape of $C$ is $m \times p$
$$\color{orange}{C_{i,j}=\sum_kA_{i,k}B_{k,j} \tag{3}}$$

In [15]:
# Matrix A shape: (2,3) B shape: (3,4)
mmv_matrix_A = tf.ones([2,3], name="matrix_A")
mmv_matrix_B = tf.constant([[1,2,3,4], [1,2,3,4], [1,2,3,4]], name="matrix_B", dtype=tf.float32)

# Matrix C: C=AB, C shape: (2,4)
matrix_multiply_C = tf.matmul(mmv_matrix_A, mmv_matrix_B, name="matrix_multiply_C")

print("""Matrix A: shape {0} \nelements: \n{1}\
\n\nMatrix B: shape {2} \nelements: \n{3}\
\nMatrix C: shape {4} \nelements: \n{5}""".format(mmv_matrix_A.shape, mmv_matrix_A,
                                                  mmv_matrix_B.shape, mmv_matrix_B,
                                                  matrix_multiply_C.shape, matrix_multiply_C))

Matrix A: shape (2, 3) 
elements: 
[[1. 1. 1.]
 [1. 1. 1.]]

Matrix B: shape (3, 4) 
elements: 
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
Matrix C: shape (2, 4) 
elements: 
[[ 3.  6.  9. 12.]
 [ 3.  6.  9. 12.]]


To get a matrix containing the product of individual elements, use **element wise production** or **Handmamard product** and write $A \odot B$

In [16]:
# Matrix A, B shape (3,3)
element_matrix_A = tf.ones([3,3], name="element_matrix_A")
element_matrix_B = tf.constant([[1,2,3], [4,5,6], [7,8,9]], name="element_matrix_B", dtype=tf.float32)

# element wise product
element_wise_C = tf.multiply(element_matrix_A, element_matrix_B, name="element_wise_C")

print("""Matrix A: shape {0} \nelements: \n{1}\
\n\nMatrix A: shape {2} \nelements: \n{3}\
\nMatrix C: shape {4} \nelements: \n{5}""".format(element_matrix_A.shape, element_matrix_A,
                                                  element_matrix_B.shape, element_matrix_B,
                                                  element_wise_C.shape, element_wise_C))

Matrix A: shape (3, 3) 
elements: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Matrix A: shape (3, 3) 
elements: 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Matrix C: shape (3, 3) 
elements: 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


![Dot Product](https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0202b.jpg)

In [17]:
# Matrix A, B shape: (3,3)
dot_matrix_A = tf.ones([3,3], name="dot_matrix_A")
dot_matrix_B = tf.constant([[1,2,3], [4,5,6], [7,8,9]], name="dot_matrix_B", dtype=tf.float32)

# Dot Product AB
dot_product_C = tf.tensordot(dot_matrix_A, dot_matrix_B, axes=1, name="dot_product_C")

print("""Matrix A: shape {0} \nelements: \n{1}\
\n\nMatrix B: shape {2} \nelements: \n{3}\n\
Matrix C: shape {4} \nelements: \n{5}""".format(dot_matrix_A.shape, dot_matrix_A,
                                                dot_matrix_B.shape, dot_matrix_B,
                                                dot_product_C.shape, dot_product_C))

Matrix A: shape (3, 3) 
elements: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Matrix B: shape (3, 3) 
elements: 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Matrix C: shape (3, 3) 
elements: 
[[12. 15. 18.]
 [12. 15. 18.]
 [12. 15. 18.]]



Some properties of matrix multiplication (variance properties): $$\color{orange}{A(B+C)=AB+AC\tag{4}}$$

In [18]:
matrix_A = tf.constant([[1,2], [3,4]], name="matrix_a")
matrix_B = tf.constant([[5,6], [7,8]], name="matrix_b")
matrix_C = tf.constant([[9,1], [2,3]], name="matrix_c")

In [19]:
print("Matrix A: \n{} \n\nMatrix B: \n{} \n\nMatrix C: \n{}\n".format(matrix_A, matrix_B, matrix_C))

# AB+AC
distributive_RHS = tf.add(tf.matmul(matrix_A, matrix_B), tf.matmul(matrix_A, matrix_C), name="RHS")

# A(B+C)
distributive_LHS = tf.matmul(matrix_A, (tf.add(matrix_B, matrix_C)), name="LHS")

predictor = tf.reduce_all(tf.equal(distributive_RHS, distributive_LHS))

def true_print():
    print("""Distributive property is valid RHS: AB+AC: \n{} \n\nLHS: A(B+C): \n{}""".format(distributive_RHS, distributive_LHS))

def false_print():
    print("""You Broke the Distributive Property of Matrix RHS: AB+AC: \n{}\
  \n\nis NOT Equal to LHS: A(B+C): \n{}""".format(distributive_RHS, distributive_LHS))

tf.cond(predictor, true_print, false_print)

Matrix A: 
[[1 2]
 [3 4]] 

Matrix B: 
[[5 6]
 [7 8]] 

Matrix C: 
[[9 1]
 [2 3]]

Distributive property is valid RHS: AB+AC: 
[[32 29]
 [78 65]] 

LHS: A(B+C): 
[[32 29]
 [78 65]]


Some properties of matrix multiplication (association properties):
 $$\color{orange}{A(BC)=(AB)C\tag{5}}$$

In [20]:
print("Matrix A: \n{} \n\nMatrix B: \n{} \n\nMatrix C: \n{}\n".format(matrix_A, matrix_B, matrix_C))
# (AB)C
assosiative_RHS = tf.matmul(tf.matmul(matrix_A, matrix_B), matrix_C)
# A(BC)
assosiative_LHS = tf.matmul(matrix_A, tf.matmul(matrix_B, matrix_C))
predictor = tf.reduce_all(tf.equal(assosiative_RHS, assosiative_LHS))
def true_print():
    print("""Assosiative property is valid RHS: (AB)C: \n{} \n\nLHS: A(BC): \n{}""".format(assosiative_RHS, assosiative_LHS))
def false_print():
    print("""You Broke the Assosiative Property of Matrix RHS: (AB)C): \n{}\
  \n\nis NOT Equal to LHS: A(BC): \n{}""".format(assosiative_RHS, assosiative_LHS))
tf.cond(predictor, true_print, false_print)

Matrix A: 
[[1 2]
 [3 4]] 

Matrix B: 
[[5 6]
 [7 8]] 

Matrix C: 
[[9 1]
 [2 3]]

Assosiative property is valid RHS: (AB)C: 
[[215  85]
 [487 193]] 

LHS: A(BC): 
[[215  85]
 [487 193]]


Some properties of matrix multiplication $$\color{orange}{AB \neq BA\tag{6}}$$

In [21]:
print("Matrix A: \n{} \n\nMatrix B: \n{}".format(matrix_A, matrix_B))

# Matrix A times B
commutative_RHS = tf.matmul(matrix_A, matrix_B)

# Matrix B times A
commutative_LHS = tf.matmul(matrix_B, matrix_A)

predictor = tf.logical_not(tf.reduce_all(tf.equal(commutative_RHS, commutative_LHS)))

def true_print():
    print("""Matrix Multiplication is not commutative  (AB): \n{} \n\nLHS: (BA): \n{}""".format(commutative_RHS, commutative_LHS))

def false_print():
    print("""You made Matrix Multipliccation commutative RHS: (AB): \n{}\
  \n\n LHS: (BA): \n{}""".format(commutative_RHS, commutative_LHS))

tf.cond(predictor, true_print, false_print)

Matrix A: 
[[1 2]
 [3 4]] 

Matrix B: 
[[5 6]
 [7 8]]
Matrix Multiplication is not commutative  (AB): 
[[19 22]
 [43 50]] 

LHS: (BA): 
[[23 34]
 [31 46]]


(Transpose): $$\color{orange}{(AB)^\top = B^\top A^\top\tag{7}}$$

In [22]:
print("Matrix A: \n{} \n\nMatrix B: \n{}\n".format(matrix_A, matrix_B))

transpose_RHS = tf.transpose(tf.matmul(matrix_A, matrix_B))

transpose_LHS = tf.matmul(matrix_B, matrix_A, transpose_a=True, transpose_b=True)

predictor = tf.reduce_all(tf.equal(transpose_RHS, transpose_LHS))

def true_print():
    print("""Transpose property is valid RHS: (AB)^T: \n{}\
  \n\nLHS: (B^T A^T): \n{}""".format(transpose_RHS, transpose_LHS))

def false_print():
    print("""You Broken the Transpose property of Matrix RHS: (AB)^T: \n{}\
  \n\nLHS: (B^TA^T): \n{}""".format(transpose_RHS, transpose_LHS))

tf.cond(predictor, true_print, false_print)

Matrix A: 
[[1 2]
 [3 4]] 

Matrix B: 
[[5 6]
 [7 8]]

Transpose property is valid RHS: (AB)^T: 
[[19 43]
 [22 50]]  

LHS: (B^T A^T): 
[[19 43]
 [22 50]]


### 1-3. Identity and Inverse Matrices
Linear algebra provides a powerful tool called **matrix inversion**.
Analytical resolution of $Ax=b$ for many values ​​of $A$
To explain matrix inversion, we need to first define the concept of **identity matrix**.
The identity matrix is ​​a matrix that does not change the vector when multiplied by that matrix.
$$\color{orange}{I_n \in \mathbb{R}^{n \times m} \text{and}\ \forall x \in \mathbb{R}^n, I_nx = x \tag{8} }$$

The structure of the identity matrix is ​​that all items along the main diagonal are 1 and all items are 0.

In [23]:
# matrix I
identity_matrix_I = tf.eye(3,3, dtype=tf.float32, name='IdentityMatrixI')
print("Identity matrix I: \n{}\n".format(identity_matrix_I))

iim_vector_x = tf.constant([[4], [5], [6]], name='Vector_x', dtype=tf.float32)
print("Vector x: \n{}\n".format(iim_vector_x))

iim_matrix_C = tf.matmul(identity_matrix_I, iim_vector_x, name='MatrixC')
print("Matrix C from Ix: \n{}".format(iim_matrix_C))

Identity matrix I: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Vector x: 
[[4.]
 [5.]
 [6.]]

Matrix C from Ix: 
[[4.]
 [5.]
 [6.]]


**Matrix inverse** of $A$ is expressed as $A^{-1}$ and is defined as follows
$$\color{orange}{A^{-1}A = I_n\tag{9}}$$


The equation $Ax=b$ can be solved as
$$\color{orange}{A^{-1}Ax=A^{-1}b \\
I_nx=A^{-1}b \\
x=A^{-1}b\tag{10}}$$

![Matrix Inverse](https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0203a.PNG)

Prove that a linear equation cannot have two solutions. (Eigher one or infinitely many solutions) ??

Think of the columns of $\textbf{A}$ as the different directions we can travel to from origin, then determine how many different ways we can follow to reach $\textbf{b}$.

$$ \textbf{A}\textbf{x} = \sum_{i}x_{i}\textbf{A}_{:,i}$$

If $\textbf{b}$ is in the span of the coumns of $\textbf{A}$, then $\textbf{A}\textbf{x}=\textbf{b}$ must have  a solution. In this particular case, the span is called the range or **column space** of $\textbf{A}$.

The requirement that column space of $\textbf{A}$ be all of $\mathbb{R}^{m}$ implies that $\textbf{A}$ must have atleast m columns. Otherwise dimensionalty of column space would be less than m. A an example take $\textbf{A}$ as a $3 \times 2$ matrix, that means we only have two $x_{i}$'s which can vary to produce the output. The output will lie on a 2-D plane in the 3-D space. However, this is necessary and not sufficient condition for $\textbf{A}\textbf{x}=\textbf{b}$ having a solution.

Even if the matrix has 3 columns, if two of them are the same, output for $\textbf{A}\textbf{x}$ would lie on $\mathbb{R}^{2}$. Thus the columns should also be linearly independent.

For the matrix $\textbf{A}$ to have inverse, it is required that the equation has exactly one solution for each value of $\textbf{b}$. Thus the matrix should have **m linearly independent columns**.
<br><br>
**Using Gauss-Jordan Elimination to find Inverse**

$$ \textbf{E}\begin{bmatrix} \textbf{A} & \textbf{I}\end{bmatrix} = \begin{bmatrix} \textbf{I} & \textbf{A} \end{bmatrix}$$ 

where $\textbf{E}$ is the tranformation matrix which converts the matrix $\textbf{A}$ to $\textbf{I}$ ie. it is $\textbf{A}^{-1}$.



### determinant

In [4]:
import numpy as np
a=np.array([[1,2],[4,5]])
print(a)
print(np.linalg.det(a))

[[1 2]
 [4 5]]
-2.9999999999999996


In [2]:
#inverse
a_inv=np.linalg.inv(a)
print(a)
print(a_inv)

[[1 2]
 [4 5]]
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


### pseudo inverse - for non invertible matrices with |A|=0, pseudo inverse can be calculated instead of inverse

In [9]:
a=np.array([[6,9],[3,2]])  # det(a) = 0 so inverse doesn't exist
a_pseudo_inv=np.linalg.pinv(a)
print(a)
print(a_pseudo_inv)

[[6 9]
 [3 2]]
[[-0.13333333  0.6       ]
 [ 0.2        -0.4       ]]


### Norm of a matrix

Norm can be thought as a proxy for size of matrix.
Norms are the set of functions mapping vectros to a set of non-negative values. The norm of a vector $\textbf{x}$ measures the distance between origin to the point x in the space.

$$ ||\textbf{x}||_{p} = \Big(\sum_{i}|x_{i}|^{p}\Big)^{\frac{1}{p}}$$

Formally, norm us any function that satisfies the following properties :-

- f(**x**)=0 $\implies$ x=0
- f(**x**+**y**) $\leq$ f(**x**)+f(**y**) (triangle inequality)
- $\forall \alpha \in \mathbb{R}$, f($\alpha$**x**)=$\alpha$f(**x**) 

Most common norm is the $L^{2}(\textbf{x})$ norm, also denoted as $||\textbf{x}||$. $L^{2}(\textbf{x})$ norm is the eucledian norm. $L^{2}(\textbf{x})$ norm grows very slowly near the origin so it is not used generally in ML because near origin gradients are very small and we suffer from vanishing gradient problem. Hence when we need the distance value to increase quickly near the origin we use $L^{1}(\textbf{x})$ norm. This is very important for some problems in machine learning where we need to differnciate the elements which are exactly 0 with other which are near to 0. $L^{1}(\textbf{x})$ norm grows at the same rate in all the locations. 

There are other commonly used norms defined as following :-

- $L^{0}(\textbf{x})$ norm - Number of non-zero elements in a vector $\textbf{x}$. Actually this violates the third requirement of being a norm. Still, it is mis-named as a norm.
- $L^{\infty}(\textbf{x})$ norm - Max element in the vector $\textbf{x}$
$$||\textbf{x}||_{\infty} = max_{i} |x_{i}| $$
- Frobenius Norm - $L^{2}$ norm with a martix $\textbf{A}$ instead of a vector $\textbf{x}$
$$ ||\textbf{A}||_{2} = \sqrt{\Big(\sum_{i}\sum_{j}|A_{i,j}|^{2}\Big)}$$


In [7]:
vector=np.array([1,4,46,6])

L2_norm=np.linalg.norm(vector,ord=2)
print(L2_norm)

L3_norm=np.linalg.norm(vector,ord=2)
print(L3_norm)

Linfinty_norm=np.linalg.norm(vector,ord=np.inf)
print(Linfinty_norm)

46.57252408878007
46.57252408878007
46.0


### Special Kind of Matrices 

#### Upper Triangular Matrix

#### Lower Triangular Matrix

#### Diagonal Matrices

A diagonal matrix, written as $\textbf{D}$ is a matrix in which the individual entries are defined as follows :-

$$\textbf{D}_{i,j} \neq 0 \hspace{0.1in} \forall i,j : i\neq j$$
$$\textbf{D}_{i,j} = 0 \hspace{0.1in} \forall i,j : i=j$$

This defination leads to many interesting properties as $\textbf{D}\textbf{x} = \textbf{D}\odot\textbf{x}$. This means multiplying a diagonal matrix with another vector just requires the pointwise multiplication of the corresponding elements. Also, inverting a diagonal matrix requries less number of operations as 

$$\textbf{D}^{-1} = \begin{bmatrix} \frac{1}{d_{1}} & \dotsc & \dotsc  & \dotsc \\ \dotsc & \frac{1}{d_{2}} & \dotsc  & \dotsc \\ \dotsc & \dotsc & \frac{1}{d_{i}} & \dotsc \\ \dotsc & \dotsc & \dotsc  & \frac{1}{d_{n}} \end{bmatrix}$$

Diagnomal matrix need not be square. Although, non-square diagonal matrix does not have inverse, a multiplication by these matrices is still cheap. If number of rows is greater than number of columns :-

$$ \begin{bmatrix} 1 & 0  \\ 0 & 1 \\ 0 & 0 \end{bmatrix} \begin{bmatrix} x_{1} \\ x_{2} \end{bmatrix} = \begin{bmatrix} x_{1} \\ x_{2} \\ 0 \end{bmatrix}$$

concatenate zeros to the result. If the number of columns are greater than number of rows :-

$$ \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0  \end{bmatrix} \begin{bmatrix} x_{1} \\ x_{2} \\ x_{3} \end{bmatrix} = \begin{bmatrix} x_{1} \\ x_{2}  \end{bmatrix}$$

discard last elements of $\textbf{x}$



In Machine Learning, restricting some matrices to daigonal may result in a more efficient algorithm

#### Symmetric Matrix

A matrix which is equivalent to it's own tranpose is called symmetric matrix. 

$$ \textbf{A} = \textbf{A}^{T}$$

In machine learning, symmetric matrix appear when it's entries are generated by the function having two arguments in which order of the arguments have no effect on the output of the function eg. distance metric

#### Skew-Symmytric Matrix 


#### Orthogonal/Orthonormal Matrices 

A vector $\textbf{x}$ and $\textbf{y}$ are called orthogonal if $\textbf{x}^{T}\textbf{y}=0$. If both of these vectors have non-zero norm, it means that they are at 90 degrees angle to each other. If both of the vectors have a unit norm, they are called **orthonormal**.

Orthonormal matrix is a square matrix in which both the rows and columns are mutually orthonormal to each other. For this reason :-

$$ \textbf{A}^{T}\textbf{A} = \textbf{A}\textbf{A}^{T} = I $$

This is a very important property as this implies that we can calculate the inverse of $\textbf{A}$ very quickly ($\textbf{A}^{-1} = \textbf{A}^{T}$).

#### Unitary Matrix

#### Hermitian Matrix

#### What is a linear transformation ?

To transform the vector space such that it preserves **certain properties** of the vector space structure.

T : V $\rightarrow$ W

- $\vec{0} \rightarrow \vec{0}$ ie. the null vector corresponding to vector space V should be mapped to the null vector in vector space W
- The lines which are parallel in vector space V should remain parallel in the vector space W

##### Geometric significance of linear transofmation

### Linear Algebra 2 - Solving Linear System of Equations

One common approach in mathematics is to construct a set of objects and define rules to maniuplate these objects. This is known as algebra. 

One such approach is known as linear algebra. Basically, linear algebra is the study of vectors. During early introduction  to vectors in high school years, we were introduced to them through physics classes having fourmulas such as  $ \hspace{0.1in} \vec{f} = m.\vec{a}$. Back then, we imagined vectors as a scalar which also has a direction. We understood them through a geometric interpretation with an arrow. The length of the arrow dentote the magnitude and the head of the arrow pointed towards the direction of the vector.

Moving on to the fresher/sophomore year in university, we were introduced to vectors as an abstract concept. 

Finally, for people who have pursued degrees in engineering disciplines, vector appeared in another avatar $\mathbb{R}^{n}$ or a list of n numbers. These list of number often represent some "data" which needs to be analyzed. 

In this course, we would refresh all of these interpretations and try to connect them in a coherent manner. We would use the "school" interpretation of vectors to help visualize and understand "university-fresher" and "engineer" representation. Another point to be noted is that this course is bit leaning towards the "university-fresher" representation of the matrix as it forms basis of linear algebra. Some resources pertaining other interpretations are listed below in this document.

**What is a vector?**

Vector is a special entity which can be added together and multiplied by scalars to produce another object which is also a vector.

- Geometric Vectors - Two geometric vectors $\textbf{x},\textbf{y}$ can be added leading to another vector $\textbf{z}$. They can also be multiplied by a scalar $\lambda \in \mathbb{R}$ and the result is again a vector. Therefor geometric vectors are instances of the vector concepts defined above.

- Polynomials ??
    - Addition of two polynomials result in another polynomial
    - Multiplication of a polynomial with a scalar also results in a polynomial
    - Most importantly, elements of $\mathbb{R}^{n}$, the tuple of n real numbers are also vectors.
    
<img src="Vectors_Polynomials.png" width=600 height=300 >    

**Closure of space**

One of the interesting ideas in algebra, or more generally in mathematics is "closure". It means what are the set of entities which can be obtained after performing the proposed operations. In the context of vectors, what are the set of vectors we obtain starting with a small set of vectors, adding them to each other and scaling them. This is called **vector space**.

**The concept of vector space forms the basis of much of machine learning**


**System of linear equations and how to solve them ?**

Why are we learning this ? 

Because it helps to :-

- Determine if the set of vectors are linearly dependent
- Determine the rank of a matrix
- Determine the basis of vector space
- Compute determinent of a matrix
- Determine if a vector $\textbf{b} \in \mathbb{R}^{m}$ is in the span of columns of $\textbf{A} \in \mathbb{R}^{m\times n}$ by solving $\textbf{A}\textbf{x}=\textbf{b}$. If $m > n$, then then the column space has less number of dimensions than output space. COMPLETE THIS

What would we learn in this section ?

- Particular and general solutions to the equation
- Importance of Row Echelon and Reduced Row Echelon Form of a matrix
- Gauss Elimination

A set of equations can have unique solution, no solution or infinitely many solutions.

Set 1
$$ x_{1} + x_{2} + x_{3} = 3  $$
$$ x_{1} - x_{2} + 2x_{3} = 2 $$
$$ 2x_{1} + 3x_{3} = 1 $$

Set 2
$$ x_{1} + x_{2} + x_{3} = 3  $$
$$ x_{1} - x_{2} + 2x_{3} = 2 $$
$$ x_{2} + x_{3} = 2 $$

Set 3
$$ x_{1} + x_{2} + x_{3} = 3  $$
$$ x_{1} - 2x_{2} + x_{3} = 2 $$
$$ 2x_{1} + 3x_{3} = 5 $$

$$ \textbf{a}  = \begin{bmatrix} a_{1} \\ a_{2} \\ \vdots \\ a_{n}\end{bmatrix}$$


Let us change the way we write the above equations

\begin{align}
x_{1}\begin{bmatrix}a_{11}\\\vdots\\a_{m1}\end{bmatrix}+x_{2}\begin{bmatrix}a_{12}\\\vdots\\a_{m2}\end{bmatrix}+\cdots+x_{n}\begin{bmatrix}a_{1n}\\\vdots\\a_{mn}\end{bmatrix} = \begin{bmatrix}b_{1}\\\vdots\\b_{m}\end{bmatrix} \Leftrightarrow   \begin{bmatrix} a_{11} & \cdots & a_{1n}\\ \vdots & \vdots & \vdots \\ a_{m1} & \cdots & a_{mn}\end{bmatrix} \begin{bmatrix} x_{1}\\ \vdots \\ x_{n}\end{bmatrix}=\begin{bmatrix} b_{1}\\ \vdots \\ b_{n}\end{bmatrix}
\end{align}

On the right side is something we call the compact representation of linear system of equations. We can write it as :-

$$ \textbf{A}\textbf{x} = \textbf{b}$$

Note that this representation multiplies columns of the matrix with the individual entries in vector $\textbf{x}$.

There is no rigid format to write the variable vector to the right of coefficient matrix. We can also write the variable vector to the left of the coefficient vector as below :-

$$ x_{1}\begin{bmatrix} a_{11} & \cdots & a_{1m} \end{bmatrix} + x_{2}\begin{bmatrix} a_{21} & \cdots & a_{2m} \end{bmatrix} + \cdots + x_{n} \begin{bmatrix} a_{11} & \cdots & a_{1m} \end{bmatrix} \Leftrightarrow   \begin{bmatrix} x_{1} & \cdots & x_{n} \end{bmatrix} \begin{bmatrix} a_{11} & \cdots & a_{1n} \\ \vdots & \vdots & \vdots \\ a_{m1} & \cdots & a_{mn}\end{bmatrix} = \begin{bmatrix} b_{1} & \cdots & b_{n}\end{bmatrix}$$

Note that this representation involves multiplying rows of the matrix with individual entries of the transpose of the vector $\textbf{x}$. In a compact representation, we can write it as :-

$$ \textbf{x}^{T}\textbf{A} = \textbf{b}^{T}$$

Let's digress a bit towards something called a **matrix**. A matrix is a set of vector which can be used to compactly represent linear equations and linear transformations of a vector space.

**Solving the linear system of equations**



Suppose we are given a system of linear equations :-

\begin{align}
\begin{bmatrix} 1 & 0 & 8 & -4 \\ 0 & 1 & 2 & 12 \end{bmatrix}\begin{bmatrix}x_{1}\\x_{2}\\x_{3}\\x_{4}\end{bmatrix} = \begin{bmatrix}42\\8\end{bmatrix}
\end{align}

Notice the first two columns of this linear equation, do you see something there ?? We need to find the values $x_{i}$'s such that the following is satisfied :-

$$ \sum_{i=1}^{4}x_{i}\textbf{c}_{i} = \textbf{b}$$ where $\textbf{c}_{i}$ are the columns of $\textbf{A}$

**Particular Solution**

A solution to the equation can be found by taking 42 times first column and 8 times the second column.

\begin{align}
b=\begin{bmatrix} 42 \\ 8\end{bmatrix} = 42\begin{bmatrix} 1 \\ 0\end{bmatrix}+8\begin{bmatrix} 0 \\ 1\end{bmatrix}
\end{align}

So one **particular solution** to the equation is $[42,8,0,0]^{T}$. However, this is not the only solution to the above equations. So what do we need to do to find all the other solutions to the above equation ??

**General Solution**

To find the other solutions, we need to generate 0 using the existing columns in a non-trivial way. Adding 0 to the **particular solution** does not change the solution. 

To do so, we can express any other column as the sum of first two columns. For the third column, we can write

\begin{align}
\begin{bmatrix} 8 \\ 2\end{bmatrix} = 8\begin{bmatrix} 1 \\ 0\end{bmatrix}+2\begin{bmatrix} 0 \\ 1\end{bmatrix}
\end{align}

This means that $8\textbf{c}_{1}+2\textbf{c}_{2}-1\textbf{c}_{3}+0\textbf{c}_{4}= \textbf{0}$ and $[8,2,-1,0]^{T}$ is a solution of $\textbf{A}\textbf{x}=\textbf{0}$. In fact, any scaling of $[8,2,-1,0]^{T}$ by $\lambda_{1} \in \mathbb{R}$ produces the $\textbf{0}$ vector.

\begin{align}
\begin{bmatrix} 1 & 0 & 8 & -4 \\ 0 & 1 & 2 & 12 \end{bmatrix} \begin{pmatrix} \lambda_{1}\begin{bmatrix}8\\2\\-1\\0\end{bmatrix} \end{pmatrix}= \begin{bmatrix}0\\0\end{bmatrix}
\end{align}

Similarly, we can denote the fourth column as the sum of first two columns.

\begin{align}
\begin{bmatrix} 1 & 0 & 8 & -4 \\ 0 & 1 & 2 & 12 \end{bmatrix} \begin{pmatrix} \lambda_{1}\begin{bmatrix}-4\\12\\0\\-1\end{bmatrix} \end{pmatrix}= \begin{bmatrix}0\\0\end{bmatrix}
\end{align}

Finally, putting eveything together, we obtain a general solution to the linear system of equations which we call **general solution**.

\begin{align}
x=\begin{bmatrix}42\\8\\0\\0\end{bmatrix} + \begin{pmatrix} \lambda_{1}\begin{bmatrix}8\\2\\-1\\0\end{bmatrix} \end{pmatrix} + \begin{pmatrix} \lambda_{1}\begin{bmatrix}-4\\12\\0\\-1\end{bmatrix} \end{pmatrix}, \lambda_{1},\lambda_{2} \in \mathbb{R}
\end{align}


**Steps for finding the general solution of a equation**

- Find a particular solution to $\textbf{A}\textbf{x}=\textbf{b}$
- Find all solutions to $\textbf{A}\textbf{x}=\textbf{0}$
- Combine step 1 and 2 to get a general solution

Suppose we are given any other system of equation, the above method may not directly apply on it because it may not have a convinent form that allowed us to find a particular and general solution by inspection. So, we need a definate way of transforming linear equation system into simple form. This is called **Gaussian Elimination**.

Before we go onto learning about Gaussian elimination, we need to know a key idea - **Elementary Transformations**. These transformations keep the solution to the set equations the same.

- Exchange of two equations (or row in the matrix representing the equation system)
- Multiplication of an equation with a constant $\lambda \in \mathbb{R} \setminus \{0\}$
- Addition of an equation(row) to another equation(row)

Now find the solution for the given linear system of equations :-

$$ -2x_{1} + 4x_{2} - 2x_{3} - x_{4} + 4x_{5} = -3 $$
$$ 4x_{1} - 8x_{2} + 3x_{3} - 3x_{4} + x_{5} = 2 $$
$$ x_{1} - 2x_{2} + x_{3} - x_{4} + x_{5} = 0 $$
$$ x_{1} - 2x_{2} - 3x_{4} + 4x_{5} = a$$

where $a \in \mathbb{R}$

Solve using augmented matrix. 


\begin{equation}
\begin{bmatrix}-2 & 4 & -2 & -1 & 4 &  -3\\  4 & -8 & 3 & -3 & 1 &  2\\  1 & -2 & 1 & -1 & 1 &  0\\ 1 & -2 & 0 & -3 & 4 &  a\\ \end{bmatrix}
\end{equation}

We should try to apply the above three operations in such a way that we get a structure "simiar" to that of the previous equation.

Step 1 Take the row with least first element to the top row. Here we exchange the first row with the third row. $R_{1} \leftrightarrow R_{3}$ 

\begin{equation}
\begin{bmatrix}  1 & -2 & 1 & -1 & 1 &  0 \\  4 & -8 & 3 & -3 & 1 &  2\\ -2 & 4 & -2 & -1 & 4 &  -3\\ 1 & -2 & 0 & -3 & 4 &  a\\ \end{bmatrix}
\end{equation}

Step 2. Now we can subtract rest of the three rows by first row such that their first element becomes 0. $R_{2} \rightarrow R_{2}-4R_{1}$, $R_{3} \rightarrow R_{3}+2R_{1}$, $R_{4} \rightarrow R_{4}-R_{1}$ 

\begin{equation}
\begin{bmatrix}  1 & -2 & 1 & -1 & 1 &  0 \\  0 & 0 & -1 & 1 & -3 &  2\\ 0 & 0 & 0 & -3 & 6 &  -3\\ 0 & 0 & -1 & -2 & 3 &  a\\ \end{bmatrix}
\end{equation}

Step 3. Again we see that both row 2 and row 4 has same first non-zero element ie -1. Hence, $R_{4} \rightarrow R_{4} - R_{2}$

\begin{equation}
\begin{bmatrix}  1 & -2 & 1 & -1 & 1 &  0 \\  0 & 0 & -1 & 1 & -3 &  2\\ 0 & 0 & 0 & -3 & 6 &  -3\\ 0 & 0 & 0 & -3 & 6 &  a-2\\ \end{bmatrix}
\end{equation}

Step 4. Complete rest of the reduction procedure on your own. Finally you would have the following matrix :-

\begin{equation}
\begin{bmatrix}  1 & -2 & 1 & -1 & 1 &  0 \\  0 & 0 & -1 & 1 & 3 &  -2\\ 0 & 0 & 0 & 1 & -2 &  1\\ 0 & 0 & 0 & 0 & 0 &  a+1\\ \end{bmatrix}
\end{equation}

But still, we havn't done anything to solve the equation. We have just reduced it to the form which can be solved conveniently. This is called row echelon form (REF). Reverting back to the equation format, we get :-

$$ x_{1} - 2x_{2} +x_{3}-x_{4}+x{5} = 0$$
$$ x_{3}-x_{4}+3x_{5} = -2$$
$$ x_{4}-2x_{5}=1$$
$$ 0 = a+1$$

**Can you find the particular and general solution to the equation now ?**


**Pivot and the Staircase Structure**

The leading coefficient of the row is called pivot and is always strictly to the right of the leading coefficient of the row above it. This makes sure that equation system in row echelon form has "staircase structure". 

**Row Echelon Form**

- All the nonzero rows are above any rows of all zeros . If there are rows with all zero elements, they must belong to the bottom of the matrix.
- The leading coefficient of nonzero row is always strictly to the right of the leading coefficient of the row above it.

The variables correspopnding to the pivots in row echelon form are called **basic variables**. Other variables are called **free variables**. In the example above, $x_{1},x_{3},x_{4}$ are basic variables and $x_{2},x_{5}$ are free variables.

**What are the benefits of reduced row echelon form ?**

\begin{equation}
\begin{bmatrix}  1 & -2 & 1 & -1 & 1 &  0 \\  0 & 0 & -1 & 1 & -3 &  -2\\ 0 & 0 & 0 & 1 & -2 &  1\\ 0 & 0 & 0 & 0 & 0 &  a+1\\ \end{bmatrix}
\end{equation}

Let's look at the elements corresponding to the columns which have pivot variables. This means that the second and fourth column can be removed.

\begin{equation}
\begin{bmatrix}  1  & 1 & -1 &  0 \\  0 & 1  & -1 &  -2\\ 0 & 0  & 1 &  1\\ 0 & 0  & 0 &  a+1\\ \end{bmatrix}
\end{equation}

We can express the right hand side of the equation system using the pivot columns, such that $b=\sum_{i=1}^{P}\lambda_{i}p_{i}$ where $p_{i}$ are the pivot columns. we can determine $\lambda_{i}$ in a convenient manner if we start from the right most pivot column and work our way towards the left. For the example above, we try to find $\lambda_{1},\lambda_{2},\lambda_{3}$ such that

\begin{align}
\lambda_{1}\begin{bmatrix}1\\0\\0\\0\end{bmatrix}+\lambda_{2}\begin{bmatrix}1\\1\\0\\0\end{bmatrix}+\lambda_{3}\begin{bmatrix}-1\\-1\\1\\0\end{bmatrix} = \begin{bmatrix}0\\-2\\1\\0\end{bmatrix}
\end{align}

Now, working from the right-most pivot column, we can work our way towards the left. 

**Reduced Row Echelon Form**

An equation is set to be in reduced row echelon form when :-

- It is in row echelon form
- Every pivot must be 1
- The pivot is only non-zero entry in its column

Reduced Row Echelon Form helps us in finding general solution to the set of equations. The key for finding the seolutions of $\textbf{A}\textbf{x}=\textbf{0}$ is to look at the *non-pivot columns* which we need to express as a linear combination of the pivot columns. The RREF makes this easier through as we can express the non-pivot columns in terms of the sums and multiples of pivot columns on their left. As an example take the following matrix :-

\begin{align}
A=\begin{bmatrix}1 & 3 & 0 & 0 & 3 \\ 0 & 0 & 1 & 0 & 9 \\ 0 & 0 & 0 & 1 & -4\end{bmatrix}
\end{align}

The above matrix is in RREF. We can express the second column as 3 times the first column; in the same way, fifth column can be expressed as 3 times the first column, 9 times the third column and -4 times the fourth column. Hence the solution to $\textbf{A}\textbf{x}=\textbf{0}$ are :-

\begin{align}
x = \lambda_{1}\begin{bmatrix}3\\-1\\0\\0\\0\end{bmatrix}+\lambda_{2}\begin{bmatrix}3\\0\\9\\-4\\1\end{bmatrix} \lambda_{1},\lambda_{2} \in \mathbb{R}
\end{align}

The solution to the equation  $\textbf{A}\textbf{x}=\textbf{0}$ is called the null space of matrix A

https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html

In [10]:
# Solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8:

a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
print(x)

[2. 3.]
